package ejemplo03.persistencia.dao.impl;
// Generated 19-feb-2019 10:30:03 by Hibernate Tools 4.3.1



/**
 * Contaminantes generated by hbm2java
 */
public class Contaminantes  implements java.io.Serializable {


     private String codContaminante;
     private String descContaminante;

    public Contaminantes() {
    }

	
    public Contaminantes(String codContaminante) {
        this.codContaminante = codContaminante;
    }
    public Contaminantes(String codContaminante, String descContaminante) {
       this.codContaminante = codContaminante;
       this.descContaminante = descContaminante;
    }
   
    public String getCodContaminante() {
        return this.codContaminante;
    }
    
    public void setCodContaminante(String codContaminante) {
        this.codContaminante = codContaminante;
    }
    public String getDescContaminante() {
        return this.descContaminante;
    }
    
    public void setDescContaminante(String descContaminante) {
        this.descContaminante = descContaminante;
    }




}


