package ejemplo03.persistencia.dao.impl;
// Generated 19-feb-2019 10:30:03 by Hibernate Tools 4.3.1



/**
 * Estaciones generated by hbm2java
 */
public class Estaciones  implements java.io.Serializable {


     private int codigo;
     private String nombre;
     private String zona;
     private String direccion;
     private Integer codProvincia;
     private String nomProvincia;
     private Integer codMunicipio;
     private String descMunicipio;
     private Float latitud;
     private Float longitud;
     private Integer altitud;

    public Estaciones() {
    }

	
    public Estaciones(int codigo) {
        this.codigo = codigo;
    }
    public Estaciones(int codigo, String nombre, String zona, String direccion, Integer codProvincia, String nomProvincia, Integer codMunicipio, String descMunicipio, Float latitud, Float longitud, Integer altitud) {
       this.codigo = codigo;
       this.nombre = nombre;
       this.zona = zona;
       this.direccion = direccion;
       this.codProvincia = codProvincia;
       this.nomProvincia = nomProvincia;
       this.codMunicipio = codMunicipio;
       this.descMunicipio = descMunicipio;
       this.latitud = latitud;
       this.longitud = longitud;
       this.altitud = altitud;
    }
   
    public int getCodigo() {
        return this.codigo;
    }
    
    public void setCodigo(int codigo) {
        this.codigo = codigo;
    }
    public String getNombre() {
        return this.nombre;
    }
    
    public void setNombre(String nombre) {
        this.nombre = nombre;
    }
    public String getZona() {
        return this.zona;
    }
    
    public void setZona(String zona) {
        this.zona = zona;
    }
    public String getDireccion() {
        return this.direccion;
    }
    
    public void setDireccion(String direccion) {
        this.direccion = direccion;
    }
    public Integer getCodProvincia() {
        return this.codProvincia;
    }
    
    public void setCodProvincia(Integer codProvincia) {
        this.codProvincia = codProvincia;
    }
    public String getNomProvincia() {
        return this.nomProvincia;
    }
    
    public void setNomProvincia(String nomProvincia) {
        this.nomProvincia = nomProvincia;
    }
    public Integer getCodMunicipio() {
        return this.codMunicipio;
    }
    
    public void setCodMunicipio(Integer codMunicipio) {
        this.codMunicipio = codMunicipio;
    }
    public String getDescMunicipio() {
        return this.descMunicipio;
    }
    
    public void setDescMunicipio(String descMunicipio) {
        this.descMunicipio = descMunicipio;
    }
    public Float getLatitud() {
        return this.latitud;
    }
    
    public void setLatitud(Float latitud) {
        this.latitud = latitud;
    }
    public Float getLongitud() {
        return this.longitud;
    }
    
    public void setLongitud(Float longitud) {
        this.longitud = longitud;
    }
    public Integer getAltitud() {
        return this.altitud;
    }
    
    public void setAltitud(Integer altitud) {
        this.altitud = altitud;
    }




}


