package ejemplo03.dominio;
// Generated 21-feb-2019 11:28:47 by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * Contaminantes generated by hbm2java
 */
public class Contaminantes  implements java.io.Serializable {


     private String codContaminante;
     private String descContaminante;
     private Set estaminanteses = new HashSet(0);

    public Contaminantes() {
    }

	
    public Contaminantes(String codContaminante) {
        this.codContaminante = codContaminante;
    }
    
    public Contaminantes(String codContaminante, String descContaminante, Set estaminanteses) {
       this.codContaminante = codContaminante;
       this.descContaminante = descContaminante;
       this.estaminanteses = estaminanteses;
    }
   
    public String getCodContaminante() {
        return this.codContaminante;
    }
    
    public void setCodContaminante(String codContaminante) {
        this.codContaminante = codContaminante;
    }
    public String getDescContaminante() {
        return this.descContaminante;
    }
    
    public void setDescContaminante(String descContaminante) {
        this.descContaminante = descContaminante;
    }
    public Set getEstaminanteses() {
        return this.estaminanteses;
    }
    
    public void setEstaminanteses(Set estaminanteses) {
        this.estaminanteses = estaminanteses;
    }




}


